ALG: CROSSQ
EXP_NAME: crossq

PIXEL_BASED: True
NATIVE_DOWNSCALING: True

LEARNING_RATE: 0.0003
GAMMA: 0.99
BATCH_SIZE: 64 
BUFFER_SIZE: 50000 
LEARNING_STARTS: 40000
TRAIN_FREQUENCY: 4
GRADIENT_STEPS: 16

POLICY_DELAY: 3
ALPHA_MIN: 1e-4
ALPHA_MAX: 1e4

BATCHNORM_MOMENTUM: 0.99
BRN_WARMUP_STEPS: 100000
BRN_RELAXATION_STEPS: 100000
BRN_RMAX: 3.0
BRN_DMAX: 5.0

AUTOTUNE: True
TARGET_ENTROPY_SCALE: 0.89
ALPHA: 0.2

USE_TARGET_NETWORK: False
TAU: 1.0
TARGET_UPDATE_FREQUENCY: 8000

SCAN_STEPS: 1000
NUM_ENVS: 16
TOTAL_TIMESTEPS: 10000000